---
# Copyright 2024 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Tear down CDP Public Cloud infrastructure, Environment, and Datalake
  hosts: localhost
  connection: local
  gather_facts: no
  tags:
    - env
  tasks:
    - name: Check for existing Terraform state file
      ansible.builtin.stat:
        path: tf-cdp-env/terraform.tfstate
      register: __tf_state

    - name: Terraform destroy to remove the CDP env & cloud infrastructure
      cloud.terraform.terraform: 
        project_path: "tf-cdp-env/"
        state: "absent"
        force_init: "{{ not __tf_state.stat.exists }}"

    - name: Remove the TF input and state file for Terraform module
      ansible.builtin.file:
        path: "tf-cdp-env/{{ item }}"
        state: "absent"
      loop:
        - terraform.tfvars
        - terraform.tfstate